### ISSUE TITLE
false negatives

### ISSUE THREAD

**Issue by barbalex** [afram/is-uuid#4]
Testing these two uuid's returns false:
- c9cfe3e0-e298-7a36-9c88-7c2acf143bab
- c9cfe3e0-e298-7a36-9c88-7c2acf144eec

Whereas
```js
!/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test('c9cfe3e0-e298-7a36-9c88-7c2acf143bab')
```
is true.

Above test from here: https://stackoverflow.com/a/13653180/712005

See live example here: https://codesandbox.io/s/empty-wind-11jxf

**Comment by afram** [comment]
Hi, I'm not so sure those examples are valid UUIDs, and the regex you are using doesn't appear to be the same valid one from the example.

The RFC 4122 spec denotes that the version number should be set as the 4 most significant bits of the `time-high-and-version` block (first number of the 3rd block), and the variant is a variable number of most significant bits in the `clock-seq-and-reserved` (first number of 4th block for our use case).

Valid versions are [1 - 5] and valid variants are [89ab].

In your examples it is specifying version 7, which as far as I'm aware isn't a valid version number.

**Comment by barbalex** [comment]
> the regex you are using doesn't appear to be the same valid one from the example

Yeah: I actually copied this example in the answer below the one mentioned: https://stackoverflow.com/a/7905992/712005 which on first sight seemed same but actually is different. Sorry for the confusion.

I updated the sandbox to show testing with both regexes.

> In your examples it is specifying version 7, which as far as I'm aware isn't a valid version number

To be honest: I am not able to follow your arguments. Because I understand nothing of uuid's besides hoping that they may never collide. So I assume you are right and obviously version 7 does not exist. Weird that validator says they are correct though.

**Comment by barbalex** [comment]
I checked and found out that these two UUID's were entered manually into our database. So that was probably just a simple error from someone like me who did not know what he was doing :-(

Thanks for this great tool.

Closing.

**Comment by afram** [comment]
The reason `validator` is giving you a false positive is because their regex is wrong.
https://github.com/validatorjs/validator.js/blob/c26558103efd228430f8437f68ee46c78ef8aceb/lib/isUUID.js#L16

I've raised a ticket with them
https://github.com/validatorjs/validator.js/issues/1088

**Comment by barbalex** [comment]
> I've raised a ticket with them

Me too (closed again). Long live open source ;-)

**Comment by afram** [comment]
\0/ 

Thanks for taking the time to put together comprehensive examples and test cases :-)
